[Client] 타입스크립트 리팩터링 - Stars
codestates-seb/seb40_main_033 pull request #256
Opened 2023-01-31 14:19 UTC by dohyeons

## 이슈와 연결하기

Issue Number: #253 

<br>

## 무엇이 추가 되었나요?
Star 컴포넌트들 타입스크립트 적용
<br>

## 기타 정보

<br>

2023-01-31 14:23 UTC, kihyeoon approved these changes
확인했슴다~~

2023-01-31 14:32 UTC, uxolrv requested changes

2023-01-31 14:32 UTC, uxolrv commented on client/src/components/Stars/BtnStar.tsx
> +	handleStar: (e: React.MouseEvent<SVGElement, MouseEvent>) => void;
```ts
handleStar: React.MouseEventHandler<SVGElement>
```

handleStar 함수가 별도로 뭔가를 리턴하는 게 아니고 void라면
이렇게 핸들러 함수 자체에 타입을 지정하면 `=> void` 이 부분을 생략할 수 있을 것 같아요!!

2023-01-31 14:32 UTC, uxolrv commented on client/src/components/Stars/BtnStar.tsx
> +			const eventTarget = e.target as HTMLButtonElement;
제가 아까해보니까 

```ts
const { localName, id } = e.target as HTMLButtonElement
```

이렇게 구조분해할당으로 받아오는 게 더 깔끔하더라구요!

2023-01-31 14:32 UTC, uxolrv commented on client/src/components/Stars/TextStar.tsx
> +	onClick?: () => void;
```ts
onClick: React.MouseEventHandler<HTMLInputElement>
```
이렇게 하면 에러나나요 혹시?

2023-01-31 14:38 UTC, dohyeons commented on client/src/components/Stars/TextStar.tsx
> +	onClick?: () => void;
왕 안나네엽

2023-01-31 14:45 UTC, dohyeons commented on client/src/components/Stars/BtnStar.tsx
> +	handleStar: (e: React.MouseEvent<SVGElement, MouseEvent>) => void;
넵 해씀미다
```
handleStar: (e: React.MouseEvent<SVGElement, MouseEvent>) => void;
```
와의 정확한 차이가 뭔가여 근데? 🧐

2023-01-31 14:47 UTC, dohyeons commented on client/src/components/Stars/BtnStar.tsx
> +			const eventTarget = e.target as HTMLButtonElement;
> 제가 아까해보니까
> 
> ```ts
> const { localName, id } = e.target as HTMLButtonElement
> ```
> 
> 이렇게 구조분해할당으로 받아오는 게 더 깔끔하더라구요!

아하 그렇네욥!

2023-01-31 15:13 UTC, dohyeons commented on client/src/components/Stars/TextStar.tsx
> +	onClick?: () => void;
> ```ts
> onClick: React.MouseEventHandler<HTMLInputElement>
> ```
> 
> 이렇게 하면 에러나나요 혹시?

그런데 더 정확하게는 
```
onClick?: React.MouseEventHandler<HTMLDivElement>;
```
이렇게 써주는게 좋을거 같아여

2023-01-31 16:23 UTC, kihyeoon commented on client/src/components/Stars/BtnStar.tsx
> +	handleStar: (e: React.MouseEvent<SVGElement, MouseEvent>) => void;
`React.MouseEvent<SVGElement, MouseEvent>`는 이벤트를 받고 void를 반환하는 전통적인 사용법입니다. 
`React.MouseEventHandler<SVGElement>`는 `(e: React.MouseEvent<SVGElement>) => void`와 동일한 `React.MouseEventHandler`라는 React 라이브러리의 타입을 사용하는 숏컷입니다. 
따라서 본질적으로 동일하지만 후자가 더 나은 코드 가독성을 제공하면서 더 간결한 방법입니다.

2023-02-01 01:43 UTC, uxolrv approved these changes

2023-02-01 01:44 UTC, merged