[Client] 타입스크립트 리팩터링 - Main 페이지, 케러셀
codestates-seb/seb40_main_033 pull request #268
Opened 2023-02-04 09:48 UTC by kihyeoon

## 이슈와 연결하기

Issue Number: #264

<br>

## 무엇이 추가 되었나요?

메인페이지 리펙터링 완료.

assets 폴더에 상용구 관리 폴더인 constants를 만들었습니다.

<br>

## 기타 정보

<br>

2023-02-04 14:43 UTC, uxolrv approved these changes

2023-02-04 14:43 UTC, uxolrv commented on client/src/assets/constants/MainCaroucel-Info.ts
> +const MAINCAROUCELINFO = [
왕 아예 폴더까지 constants로 만드셔서 따로 빼두시니까 깔끔하고 좋네여! 저도 constants 파일 이쪽으로 옮겨야겠어요~

2023-02-10 08:47 UTC, uxolrv requested changes

2023-02-10 08:47 UTC, uxolrv commented on client/src/types/main.type.ts
>  export interface IMainPageItem {
Interface명 앞에 I를 붙이던 것이 다른 언어에서 쓰던 관습이라고 하더라구여!
그리고 Interface명 앞에 I를 붙이는 것을 타입스크립트에서는 권장하지 않는다고 하네여
이름을 바꾸시는 게 어떨까요?

---
참고
https://radlohead.gitbook.io/typescript-deep-dive/styleguide#undefined-2
https://zereight.tistory.com/948

2023-02-11 02:20 UTC, kihyeoon commented on client/src/assets/constants/MainCaroucel-Info.ts
> +const MAINCAROUCELINFO = [
좋아요~ 그럼 assets에 바로 만들면 될까요?

2023-02-11 02:23 UTC, kihyeoon commented on client/src/types/main.type.ts
>  export interface IMainPageItem {
이게 헝가리언이었군요 ㅋㅋㅋ 넵 다른거로 바꿔보겠습니다!

2023-03-09 05:44 UTC, dohyeons commented on client/src/types/main.type.ts
>  export interface IMainPageItem {
> 이게 헝가리언이었군요 ㅋㅋㅋ 넵 다른거로 바꿔보겠습니다!

요거 안바꾸셔도 되욤~~제가 ItemCard 리팩터링 하면서 이름 바꿨습니다.~

2023-03-09 08:38 UTC, merged